site_name: Gnakry-Dev
site_url: https://gnakrydev.github.io/
site_description: "Documentation publique de Gnakry-Dev"
theme: readthedocs
site_author: "SAVOIR-GUINEE"
copyright: "SAVOIR-GUINEE - 2022"
nav:
  - À propos: "index.md"
  - Outils: "outils.md"
  - Réseau scocial: "scocial.md"
